<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/binhnguyeeen/binhnguyeeen/output/snake-dark.svg" />
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/binhnguyeeen/binhnguyeeen/output/snake.svg" />
  <img alt="contribution snake" src="https://raw.githubusercontent.com/binhnguyeeen/binhnguyeeen/output/snake.svg" />
</picture>
